version: "3.9"

services:
    replica1:
        build: .
        ports:
            - "8082:8085"
        networks:
            mynet:
                ipv4_address: 10.10.0.2
        environment:
            SOCKET_ADDRESS: "10.10.0.2:8085"
            VIEW: "10.10.0.2:8085,10.10.0.3:8085,10.10.0.4:8085"
    replica2:
        build: .
        ports:
            - "8083:8085"
        networks:
            mynet:
                ipv4_address: 10.10.0.3
        environment:
            SOCKET_ADDRESS: "10.10.0.3:8085"
            VIEW: "10.10.0.2:8085,10.10.0.3:8085,10.10.0.4:8085"
    replica3:
        build: .
        ports:
            - "8084:8085"
        networks:
            mynet:
                ipv4_address: 10.10.0.4
        environment:
            SOCKET_ADDRESS: "10.10.0.4:8085"
            VIEW: "10.10.0.2:8085,10.10.0.3:8085,10.10.0.4:8085"
networks:
    mynet:
        ipam:
            driver: default
            config:
                - subnet: 10.10.0.0/16